
import type { Metadata } from "next";
import "./globals.css";
import { font } from "@/app/fonts";
import StoreProvider from "./storeProvider";
import {Toaster} from 'react-hot-toast'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { SocketProvider } from "./socketProvider";
import { SessionProvider } from "next-auth/react";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <SocketProvider>
    <html lang="en">
      <body
        className={` ${font.className} antialiased`}
      >
        <StoreProvider>
        <div>
          {children}
          <Toaster />
          
        </div>
        </StoreProvider>
      </body>
    </html>
    </SocketProvider>
    </SessionProvider>
  );
}

